stages:
  - build
  - release

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

build-release:
  stage: release
  image: rust:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
  artifacts:
    untracked: true
    when: on_success
    access: all
    paths: 
      - tpaws.tar.gz
      - tpaws.rb

# release-job:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   needs:
#     - job: prepare-job
#       artifacts: true
#     - job: build-job
#   script:
#     - echo "======== RELEASE JOB ========"
#   rules:
#     - if: $CI_COMMIT_TAG
#   release: 
#     tag_name: "v$PKG_VERSION" 
#     description: "Awesome Web v$PKG_VERSION"
#     ref: "$CI_COMMIT_SHA" # The tag is created from the pipeline SHA.
#     assets:
#       links:
#         - name: "v$PKG_VERSION"
#           url: "${PKG_REGISTRY_URL}/x86_64-unknown-linux-gnu/v${PKG_VERSION}/asm-web"
