stages:
  - build
  - release

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

build-release:
  stage: release
  image: rust:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - cargo build --release
  artifacts:
    untracked: false
    when: on_success
    access: all
    paths: 
      - ./tpaws.tar.gz
      - ./tpaws.rb
