# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Formula
          path: tpaws.rb
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Formula

      - name: Update Formula
        run: |
          git clone git@github.com:rawnly/homebrew-worktools
          cp tpaws.rb ./homebrew-worktools

          cd homebrew-worktools
          git add ./tpaws.rb
          git commit -m 'feat(tpaws): new release'
          git push -u origin $(git rev-parse --abbrev-ref HEAD)

          git config set user.name 'github-actions[bot]'
          git config set user.email 'rawnly@users.noreply.github.com'

          echo "COMMIT HASH \"$(git log -1 --foramt=%H)\""
